# Generated by Django 3.1.4 on 2021-07-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
