# Generated by Django 3.1.4 on 2021-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0002_auto_20210727_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
