# Generated by Django 3.1.2 on 2021-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0004_auto_20211022_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
