# Generated by Django 3.1.2 on 2021-12-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0005_auto_20211209_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='dateOfExtraction',
            field=models.DateField(default='-'),
        ),
        migrations.AddField(
            model_name='news_post',
            name='link',
            field=models.CharField(default='link_not_available', max_length=250),
        ),
        migrations.AddField(
            model_name='news_post',
            name='source',
            field=models.CharField(default='Source not available', max_length=250),
        ),
    ]
